### ISSUE TITLE
split got me throw a JsonWriterException: Unclosed JSON objects and/or arrays when closing writer

### ISSUE THREAD

**Issue by FlorianSteenbuck** [mmastrac/nanojson#6]
```java
public static String getSteemitRequest(String method, Object[] params) {
        JsonStringWriter steemitRequestsWriter = JsonWriter.string().object();
        steemitRequestsWriter.value(Words.ID, getId());
        steemitRequestsWriter.value(Words.JSONRPC, Versions.SECOND_ONE_DOT);
        steemitRequestsWriter.value(Words.METHOD, method);
        steemitRequestsWriter.value(Words.PARAMS, params);
        return steemitRequestsWriter.done();
}
...
getSteemitRequest("get_content", "@sempervideo/mq3ykiml".split("/"));
```
got me this Exception:
```java
com.grack.nanojson.JsonWriterException: Unclosed JSON objects and/or arrays when closing writer
	at com.grack.nanojson.JsonWriterBase.doneInternal(Unknown Source)
	at com.grack.nanojson.JsonStringWriter.done(Unknown Source)
```
Why ?

**Comment by mmastrac** [comment]
Try `        return steemitRequestsWriter.end().done();`

**Comment by FlorianSteenbuck** [comment]
oh that simple thx
